name: MlFlow-CI
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      
      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run ./MLProject --env-manager=local
          
       # Save models to GitHub Repository
      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add mlruns/
          git commit -m "Save mlruns from CI run"
          git push origin main

      # Generate Dockerfile with MLFlow
      - name: Generate Dockerfile with MLFlow
        run: |
          MODEL_PATH=$(find mlruns -name MLmodel | head -n 1 | xargs dirname)
          mlflow models generate-dockerfile \
            -m $MODEL_PATH \
            --output-directory crops_recommendation_docker
